platform :ios, '9.0'

target 'CCQNews' do
  use_frameworks!
  pod 'AFNetworking'
  pod 'SDWebImage'
  pod 'YYModel'
  pod 'MBProgressHUD'
  pod 'MJRefresh'
  pod 'IQKeyboardManager'
  pod 'ZFPlayer'
  pod 'ZFPlayer/ControlView'
  pod 'ZFPlayer/AVPlayer'
  pod 'FDFullscreenPopGesture'
  pod 'JPush'
end
